# vim:ft=yaml.ansible
---
# tasks file for app-scripts
- name: "Copy run script"
  ansible.builtin.template:
    src: templates/run-app.sh.j2
    dest: "{{ home }}/run-app.sh"
    mode: "0755"

- name: "Copy environment file"
  ansible.builtin.copy:
    src: files/.env
    dest: "{{ git_work_tree }}/.env"
    mode: "0644"
